yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolo-feb.weights
  threshold:
    value: 0.6
  detection_classes:
    names:
      - bootlegger
      - badge
      - g-man
      - tommy-gun

